version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - /var/html/static/
      - /var/html/media/
    depends_on:
      - db
